env:
  - DOCKER_USERNAME = "hanguyenanhson455"
  - DOCKER_PASSWORD = "9?+bKsn$^rVLQ&r"
before_install:
  - echo "9?+bKsn$^rVLQ&r" | docker login -u "hanguyenanhson455" --password-stdin
  - docker pull mediasol/openjdk17-slim-jprofiler

script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker